### ISSUE TITLE
Levels menu

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#54]
## Description
Currently, if you want to go, say, from the 200th level to the 100th level, you have to tap the left button 100 times, and it takes time. 

What could solve this is a menu which would appear when tapping the level number, for example, and would contain a vertical sliding pane containing every level.

**Comment by Poolitzer** [comment]
Hey, I think thats a good improvement. Show a good overview of the levels, and indicate which you already finished and which you skipped
