### ISSUE TITLE
Gravity Box crashes on launch

### ISSUE THREAD

**Issue by happysmash27** [Luca1152/gravity-box#64]
Compiling this out of the box, the debug version crashes for some reason. I have not yet been able to run the release, since for some reason unsigned releases won't run on Android P, and I have not yet figured out how to sign a release from the command line (I am compiling via SSH from my phone on my computer which is currently on the other side of the country).

**Comment by happysmash27** [comment]
It turns out that the release version does too, even when signed. It has a black screen for a couple seconds, then just disappears…

**Comment by happysmash27** [comment]
Apparently, logcat works from my phone. The problem: no messages from Gravity Box exist.

**Comment by happysmash27** [comment]
Even when I use `-b all`, I still get nothing from Gravity Box!

**Comment by Luca1152** [comment]
I can't replicate your issue. How are you compiling the game? What command(s) are you using?
