### ISSUE TITLE
Rank doesn't update when beating the previous record on a level

### ISSUE THREAD

**Issue by thedavidhurt** [Luca1152/gravity-box#71]
On Android, when a player beats the previous record on a level, his rank doesn't seem to update correctly even though it does update the rank #&#x2060;1 tap count.

What I've seen:
1. Beat the previous rank #&#x2060;1. For example, it was 11 taps, beat it in 7.
2. Go on to the next level.
3. Open level selector and see that the level still shows unranked.
4. Open the level leaderboard and see that the rank #&#x2060;1 is still at 11 taps.
5. Close app and restart. Now the level leaderboard shows rank #&#x2060;1 at 7 taps.
6. The player's rank is still set at unranked.
7. Beat the level with 7 taps again to finally achieve rank #&#x2060;1.

**Comment by Luca1152** [comment]
Thanks for reaching out and for the detailed description, @thedavidhurt! :) I'll investigate the issue.

**Comment by Luca1152** [comment]
The issue should now be fixed in version 1.4.3, @thedavidhurt . Let me know if everything is alright, and thank you again for reporting it.

**Comment by thedavidhurt** [comment]
Thanks for getting to this so quickly! I believe this is resolved except that I think I still had to reload the app to get updated leaderboard stats. It correctly saved my rank and taps though so it's just a minor inconvenience now.

**Comment by Luca1152** [comment]
@thedavidhurt Hmm... Interesting. I thought I solved the issue of having to restart the game as well. I'll look into it.

**Comment by thedavidhurt** [comment]
Sorry, I must have been mistaken. Just checked again and the leaderboard updated correctly without a reload. Thanks!
